@startuml
'https://plantuml.com/class-diagram
class landingPage{
}
class formularAutentificare{
}
class textboxEmail{
}
class textboxParola{
}
class checkbuttonTineMinte{
}
class buttonCreareCont{
}
class buttonAutentificare{
}
class buttonUitatParola{
}
class contUtilizator{
}
class emailCont {
}
class parolaCont {
}
class formularInregistrare{
}
class textboxConfirmareParola {
}
class buttonInregistrare{
}
class bazaDateConturi{
}
class popupEmailParolaGresite{
}
class butonReincearca{
}
class HomePage{
}
class buttonDeschideInchideNavbar {
}
class Navbar {
}
class divStire{
}
class pozaStire {
}
class descriereStire {
}
class paginaStire {
}
class infoStire {
}
class buttonProfilUtilizator {
}
class paginaProfilUtilizator {
}
class buttonComparare {
}
class paginaComparare {
}
class buttonForum {
}
class paginaForum {
}
class buttonReview {
}
class paginaReview {
}
class pozaProfilCont{
}
class numeCont {
}
class infoMasina {
}
class descriereCont {
}
class buttonEditareProfil {
}
class buttonAfisarePrieteni {
}
class buttonAfisareGrupuri {
}
class buttonSetariApp {
}
class sectiuneDetaliiCont {
}
landingPage *.. formularAutentificare
landingPage *.. buttonCreareCont
formularAutentificare *.. textboxEmail
formularAutentificare *.. textboxParola
formularAutentificare *.. checkbuttonTineMinte
formularAutentificare *.. buttonUitatParola
formularAutentificare *.. buttonAutentificare
buttonAutentificare o.. HomePage
buttonAutentificare o...... bazaDateConturi
buttonCreareCont o.. formularInregistrare
formularInregistrare *.. textboxEmail
formularInregistrare *.. textboxParola
formularInregistrare *.. textboxConfirmareParola
formularInregistrare *... buttonInregistrare
bazaDateConturi o.. contUtilizator
contUtilizator *.. emailCont
contUtilizator *.. parolaCont
contUtilizator *.. numeCont
contUtilizator o.. infoMasina
contUtilizator o.. descriereCont
contUtilizator o.. pozaProfilCont
HomePage *.. buttonDeschideInchideNavbar
buttonDeschideInchideNavbar o.. Navbar
HomePage *.. divStire
divStire *.. pozaStire
divStire *.. descriereStire
divStire o.. paginaStire
paginaStire *.. infoStire
Navbar *.. buttonProfilUtilizator
Navbar *.. buttonComparare
Navbar *.. buttonForum
Navbar *.. buttonReview
buttonProfilUtilizator o.. paginaProfilUtilizator
buttonComparare o.. paginaComparare
buttonForum o.. paginaForum
buttonReview o.. paginaReview
paginaProfilUtilizator *.. sectiuneDetaliiCont
paginaProfilUtilizator *..buttonEditareProfil
paginaProfilUtilizator *.. buttonAfisareGrupuri
paginaProfilUtilizator *.. buttonAfisarePrieteni
paginaProfilUtilizator *.. buttonSetariApp
sectiuneDetaliiCont *.. pozaProfilCont
sectiuneDetaliiCont *.. numeCont
sectiuneDetaliiCont *.. infoMasina
sectiuneDetaliiCont *.. descriereCont

@enduml