@startuml
'https://plantuml.com/use-case-diagram
left to right direction
actor Utilizator as u

package LandingPage {
    usecase "Se va afisa Landing \n Page care va contine \n un mesaj 'Welcome to CarHub!' \n si un div central impartit \n in 2, in partea stanga va fi \n formularul de autentificare iar in \n dreapta formularul de inregistrare" as UC1
    usecase "Se incrementeaza numarul \n de caractere introduse si \n se compara cu numarul maxim \n de caractere limita" as UC2
    usecase "Campul nu va mai lasa \n utilizatorul sa introduca alte caractere" as UC3
    usecase "Se va afisa un pop-up din \n campul respectiv cu mesajul 'Required'" as UC4
    usecase "Se va verifica email-ul pentru duplicate" as UC5
    usecase "Se va afisa mesajul \n"Email existent"" as UC6
    usecase "Email-ul si parola se \n vor salva in baza de date" as UC7
    usecase "Formularul va tine \nminte email si parola" as UC8
    usecase "Se va deschide o pagina \n cu un textbox pentru email-ul \n utilizatorului, un textbox pentru \n parola noua, un textbox pentru \n connfirmarea parolei si un \n buton de "Schimba parola"." as UC9
    usecase "Se va trimite un request la \n baza de date de inlocuire a \n parolei vechi stocate cu cea noua" as UC11
    usecase "Se va afisa popup-ul "Parola \n schimbata cu succes" pentru \n 5 secunde si apoi va disparea, \n urmand ca pagina sa trimita utilizatorul \n inapoi pe Landing Page" as UC12
    usecase "Se va trimite un request catre baza \n de date pentru a verifica corectitudinea \n informatiei din campurile respective" as UC13
    usecase "Pagina va afisa un \n pop up cu mesajul \n"Email sau parola gresite" \n si un buton de "Reincearca"" as UC14
    usecase "Fereastra Pop-up \n se va inchide" as UC15
}

package HomePage {
    usecase "Se va afisa Home Page \n care contine in partea \n stanga un NavBar si \n in centru, Home Page va afisa \n cate un div care contine o \n poza si o scurta descriere a \n unei stiri din domeniul auto" as UC16
    usecase "Pagina va deschide \nalta pagina care \ncontine toata informatia \n legata de acea stire" as UC17
    usecase "Se incarca stirile mai vechi, \ndandu-se scroll in jos la paina" as UC18
    usecase "Se incarca stirile actuale,\n dandu-se scroll in sus la pagina" as UC19
}

package 1)Profil_Utilizator {
    usecase "Se va afisa o pagina care \n contine acelasi NavBar in partea \n stanga iar pe mijloc va fi afisata \n sectiunea detalilor contului unde \n se va afla poza de profil a utilizatorului \n impreuna cu numele acestuia langa ea,\n sub se vor afisa informatiile masinii, \n o mica descriere, buton pentru editare profil \n si un buton pentru setarile aplicatiei." as UC20
    usecase "Pagina va permite utilizatorului \n sa editeze campul de nume si campul \n de informatii ale masinii si se va \n afisa un buton de salvare a modificarilor facute" as UC21
    usecase "Se va actualiza baza de \n date cu informatiile modificate" as UC22
    usecase "Pagina va iesi \n din modul de editare." as UC23
    usecase "Se va deschide o pagina \n care contine un buton pentru \n schimbarea temei paginii si un \n buton pentru stergerea contului." as UC24
    usecase "Se va schimba pe tema opusa \n fata de optiunea curenta selectata" as UC25
    usecase "Aplicatia va avea drept \n culoare principala alb" as UC26
    usecase "Aplicatia va avea drept \n culoare principala gri graphite" as UC27
    usecase "Se va afisa o fereastra cu \n un buton de confirmare" as UC28
    usecase "Se va trimite un request \n catre baza de date pentru \n stergerea email-ului \n si parolei din evidenta" as UC29
    usecase "Se va afisa \n Landing Page" as UC30
}

package 2)Comparare_masini {
    usecase "Se va afisa o pagina care \n contine acelasi NavBar in \n partea stanga iar pe mijloc va \n fi afisat un div impartit in 2 parti: \n prima parte pentru alegerea \n primei masini , a 2 a parte pentru \n alegerea masinii 2 si un \n buton de start comparare" as UC31
    usecase "Se va afisa o lista \n aferenta fiecarui \n tip de informatie" as UC32
    usecase "Sub acest div se va afisa \n un alt div care afiseaza \n o poza pentru fiecare masina, \n sub poze se vor afisa brand-ul \n si marca masinilor, iar sub acestea \n se vor afisa informatiile legate de \n anul productiei, informatii legate \n de dimensiuni, informatii ale motoarelor, \n clasa masinilor si siguranta in caz de \n impact." as UC33
    }

package 3)Forum {
    usecase "Se va afisa o pagina \n care contine acelasi NavBar \n in partea stanga iar pe \n mijloc vor fi afisate mai \n multe cadrane cu diferite \n subiecte de discutie recente, \n un searchbar pentru a cauta \n subiecte in functie de cuvintele \n cheie scrise si un buton in \n coltul din dreapta jos al \n paginii pentru a scrie un topic." as UC34
    usecase "Se va deschide fereastra \n dedicata acelei discutiei, cu \n textul integral, data postarii, \n replicile oferite de ceilalti \n utilizatori si un textbox pentru \n a scrie o replica la o postare, \n alaturi de un buton de trimite" as UC35
    usecase "Se va posta ca replica raspunsul \n tau, sub ultima replica cea mai recenta." as UC36
    usecase "Utilizatorului ii este \n permisa scrierea cuvintelor" as UC37
    usecase "Se va executa algoritmul \n de cautare pe baza cuvintelor" as UC38
    usecase "Se vor afisa subiectele care \n au o potrivire de cuvinte" as UC39
    usecase "Se va deschide o \n fereastra de redactare \n a unui subiect de discutie" as UC40
    usecase "Subiectele de discutie se \n vor afisa in pagina 'Forum'" as UC41
}

'Landing Page
u -down-> UC1: Introduce linkul aplicatiei \n in browser si apasa enter
u -down-->UC2:Introduce caractere \n in campurile textbox
u -down-> UC3:Introduce mai mult \n de 16 caractere in campuri.
u -down-> UC4:Apasa pe 'Inregistrare' sau 'Autentificare' \n fara sa introduca caractere in textboxuri
u -down-> UC5:Completeaza campurile pentru \ninregistrare si apasa 'Inregistrare'
UC5 -down-> UC6:Daca email este duplicat
UC5 -down-> UC7:Daca email nu este duplicat
UC7 -down-> UC1
u -down-> UC8:Bifeaza checkbox\n-ul 'Tine-ma minte'
u -down-->UC9:Completeaza campurile \n si apasa butonul \n 'Am uitat parola'
u -down-->UC11:Completeaza campul si \n apasa butonul 'Schimba parola'
UC11 -down-->UC12
u -down-> UC13:Completeaza campurile pentru \nautentificare si apasa 'Autentificare'
UC13 -down-> UC14:Daca datele sunt gresite
UC13 -down--> UC16:Daca datele sunt corecte
u -down-->UC15:Apasa butonul \n 'Reincearca'


:Admin: --> (Se vor afisa stirile in Home \n Page in partea de sus):Introduce noutati si \n stiri din domeniul auto in \n div-urile din mijlocul \n Home Page-ului
:Admin: --> (Se vor afisa informatiile \n legate de masini in pagina \n de Comparare masini):Introduce informatiile \n masinilor in baza de date


'Home Page
u -down--> UC17:Apasa pe orice div din din Home Page.
u -down--> UC18:Se afla in top sau mid pe Home Page si da scroll-down
u -down--> UC19:Se afla in bottom sau mid pe Home Page si da scroll-up


'Profil Utilizator
u -up-> UC20:Apasa pe butonul \n 1.Profil utilizator
u -up-> UC21:Apasa butonul de editare profil
u -up-> UC22:Apasa butonul de salvare a modificarilor
UC22 -up-> UC23
u -up-> UC24:Apasa pe butonul de setari ale aplicatiei
u -up-> UC25:Apasa pe butonul de schimbare a temei paginii
u -up-> UC26:Alege tema light
u -up-> UC27:Alege tema dark
u -up-> UC28:Apasa butonul de stergere cont
u -up-> UC29:Apasa butonul de confirmare a stergerii contului
UC29 -up-> UC30


'Comparare masini
u -down--> UC31:Apasa pe butonul \n 2.Comparare masini
u -down--> UC32:La apasarea \n fiecarui dropdown
u -down--> UC33:La apasarea butonului \n de comparare masini


'Forum
u -up-> UC34:Apasa pe \n butonul 3.Forum
u -up-> UC35:La accesarea \n unui subiect
u -up-> UC36:La completarea textbox-ului \n si apasarea butonului trimite
u -up-> UC37:La apasarea \n searchbar-ului
u -up-> UC38:Cand utilizatorul va \n apasa enter la searchbar
UC38 -up->UC39
u -up-> UC40:La apasarea butonului din \n dreapta jos al paginii
u -up-> UC41:La completarea textbox-urilor \n si apasarea butonului incarca


@enduml
