@startuml
'https://plantuml.com/use-case-diagram
left to right direction
actor Utilizator as u

package LandingPage {
    usecase "Se va afisa Landing \n Page care va contine \n un mesaj "Welcome to CarHub!" \n si un div central impartit \n in 2, in partea stanga va fi \n formularul de autentificare iar in \n dreapta formularul de inregistrare" as UC20
    usecase "Campul nu va mai lasa \n utilizatorul sa introduca alte caractere" as UC21
    usecase "Email-ul si parola se \n vor salva in baza de date" as UC22
    usecase "Se va trimite un request \n catre baza de date cu corectitudinea \n informatiei din campurile respective" as UC23
    usecase "Formularul va tine \nminte email si parola" as UC24
    usecase "Pagina va afisa un \n pop up cu mesajul \n"Email sau parola gresite" \n si un buton de "Reincearca"" as UC25
    usecase "Fereastra Pop-up \n se va inchide" as UC26
    usecase "Se va trimite un \n email utilizatorului cum ca \n contul lui a fost creat" as UC36
    usecase "Se incrementeaza numarul \n de caractere introduse si \n se compara cu numarul maxim \n de caractere limita" as UC37
    usecase "Se va deschide o pagina cu \n un textbox pentru email-ul utilizatorului \n si un buton de "Urmatorul"" as UC38
    usecase "Va aparea un alt textbox \n pentru noua parola si \n confirmarea parolei si un \n buton cu textul "Schimba parola"" as UC39
    usecase "Se va trimite un request la \n baza de date de inlocuire a \n parolei vechi stocate cu cea noua" as UC40
    usecase "Se va afisa popup-ul "Parola \n schimbata cu succes" pentru \n 5 secunde si apoi va disparea, \n urmand ca pagina sa trimita utilizatorul \n inapoi pe Landing Page" as UC41
    usecase "Se va verifica email-ul pentru duplicate" as UC46
    usecase "Se va afisa mesaul \n"Email existent"" as UC47
}

package HomePage {
    usecase "Se va afisa Home Page \n care contine in partea \n stanga un NavBar si \n in centru, Home Page va afisa \n cate un div care contine o \n poza si o scurta descriere a \n unei stiri din domeniul auto" as UC15
    usecase "Pagina va deschide \nalta pagina care \ncontine toata informatia \n legata de acea stire" as UC17
    usecase "Se incarca stirile mai vechi, \ndandu-se scroll in jos la paina" as UC18
    usecase "Se incarca stirile actuale,\n dandu-se scroll in sus la pagina" as UC19
}

package 1)Profil_Utilizator {
    usecase "Se afiseaza pagina destinata profilului de \n utilizator care contine poza de profil, numele, \n descriere, detalii despre masina, un buton de \n editare date, un buton de afisare prieteni, buton \n de afisare grupuri si un buton destinat setarilor aplicatiei" as UC1
    usecase "Se va afisa sectiunea de \n editare a datelor si un buton \n de salvare a modificarilor" as UC2
    usecase "Se va deschide o pagina \n care contine un buton pentru\n schimbarea parolei,un buton \n pentru schimbarea temei paginii si  \n un buton pentru stergerea cotului." as UC7
    usecase "Se va afisa o pagina cu 3 variante \n de alegere: automat, light sau dark" as UC9
    usecase "Aplicatia va avea drept \n culoare principala alb" as UC10
    usecase "Aplicatia va avea drept \n culoare principala gri graphite" as UC11
    usecase "Se va afisa o fereastra cu \n un buton de confirmare" as UC12
    usecase "Se va afisa \n Landing Page" as UC13
    usecase "Se va trimite un request \n catre baza de date pentru \n stergerea email-ului \n si parolei din evidenta" as UC14
}

package 2)Comparare_masini {
    usecase "Se va afisa o pagina care \n contine acelasi NavBar in \n partea stanga iar pe mijloc va \n fi afisat un div impartit in 2 parti: \n prima parte pentru alegerea \n primei masini , a 2 a parte pentru \n alegerea masinii 2 si un \n buton de start comparare" as UC27
    usecase "Se va afisa o lista \n aferenta fiecarui \n tip de informatie" as UC28
    usecase "sub acest div se va afisa \n un alt div care afiseaza \n o poza pentru fiecare masina, \n sub poze se vor afisa brand-ul \n si marca masinilor, iar sub acestea \n se vor afisa informatiile legate de \n anul productiei, informatii legate \n de dimensiuni, informatii ale motoarelor, \n clasa masinilor si siguranta in caz de \n impact. De asemenea, va exista si o rubrica \n de review-uri lasate de proprietarii masinilor." as UC29
    usecase "se va deschide o pagina cu \n mai multe casute, fiecare \n casuta afisand numele utilizatorului, \n rating-ul pe care l-a acordat \n si o parere personala" as UC30
}

package 3)Forum {
    usecase "se va afisa o pagina care \n contine acelasi NavBar in partea \n stanga iar pe mijloc vor fi \n afisate mai multe cadrane cu \n diferite subiecte de discutie recente \n si un searchbar pentru a cauta subiecte \n in functie de cuvintele cheie scrise" as UC31
    usecase "se va deschide pagina \n dedicata acelei discutii,\n cu textul integral, \n data postarii si replicile \n oferite de ceilalti utilizatori" as UC32
    usecase "utilizatorului ii este \n permisa scrierea cuvintelor" as UC33
    usecase "se va executa algoritmul \n de cautare pe baza cuvintelor" as UC34
    usecase "se vor afisa subiectele care \n au o potrivire de cuvinte" as UC35
}

'Landing Page
u -down-> UC20: Introduce linkul aplicatiei \n in browser si apasa enter
u -down-> UC46:Completeaza campurile pentru \ninregistrare si apasa 'Inregistrare'
UC46 -down-> UC47:Daca email este duplicat
UC46 -down-> UC22:Daca email nu este duplicat
u -down-> UC21:Introduce mai mult \n de 16 caractere in campuri.
UC22 -down-> UC36
UC36 -down->UC20
u -down-> UC23:Completeaza campurile pentru \nautentificare si apasa 'Autentificare'
u -down-> UC24:Bifeaza checkbox\n-ul 'Tine-ma minte'
UC23 -down-> UC25:Daca datele sunt gresite
UC23 -down--> UC15:Daca datele sunt corecte
u -down-->UC26:Apasa butonul \n 'Reincearca'
u -down-->UC37:Introduce caractere \n in campurile textbox
u -down-->UC38:Completeaza campurile \n si apasa butonul \n 'Am uitat parola'
u -down-->UC39:Completeaza campurile \n si apasa butonul 'Urmatorul'
u -down-->UC40:Completeaza campul si \n apasa butonul 'Schimba parola'
UC40 -down-->UC41


:Admin: --> (Se vor afisa stirile in Home \n Page in partea de sus):Introduce noutati si \n stiri din domeniul auto in \n div-urile din mijlocul \n Home Page-ului
:Admin: --> (Se vor afisa informatiile \n legate de masini in pagina \n de Comparare masini):Introduce informatiile \n masinilor in baza de date


'Home Page
u -down--> UC17:Apasa pe orice div din din Home Page.
u -down--> UC18:Se afla in top sau mid pe Home Page si da scroll-down
u -down--> UC19:Se afla in bottom sau mid pe Home Page si da scroll-up


'Profil Utilizator
u -up-> UC1:Apasa pe butonul \n 1.Profil utilizator
u -up-> UC2:Apasa butonul de editare profil
u -up-> UC7:Apasa pe butonul de setari ale aplicatiei
u -up-> UC9:Apasa pe butonul de schimbare a temei paginii
u -up-> UC10:Alege tema light
u -up-> UC11:Alege tema dark
u -up-> UC12:Apasa butonul de stergere cont
u -up-> UC14:Apasa butonul de confirmare a stergerii contului
UC14 -up-> UC13


'Comparare masini
u -down--> UC27:Apasa pe butonul \n 2.Comparare masini
u -down--> UC28:La apasarea \n fiecarui dropdown
u -down--> UC29:La apasarea butonului \n de comparare masini
u -down--> UC30:La apasarea ste-\nlutelor de rating


'Forum
u -up-> UC31:Apasa pe \n butonul 3.Forum
u -up-> UC32:La accesarea \n unui subiect
u -up-> UC33:La apasarea \n searchbar-ului
u -up-> UC34:Cand utilizatorul va \n apasa enter la searchbar
UC34 -up->UC35


@enduml
'gandeste d.p.d.v al aplicatiei(gandeste cum fac ele in spate)
'scriem si despre resursele web pe care le foloseste(de exemplu:foloseste imaginea din sursa x, ia info din x)
'use case = descrie functionalitate
'use case= caz de utilizare
'gandeste te la actori, daca utilizatorul este cel care face toate actiunile
'actorul este declansatorul