@startuml
'https://plantuml.com/use-case-diagram
left to right direction
actor Utilizator as u

package LandingPage {
    usecase "Se afiseaza \n Landing Page \n pe care va fi \n un formular de \n autentificare" as UC20
    usecase "Se va deschide \n o pagina cu un \n formular de inscriere" as UC21
    usecase "Email-ul si parola se \n vor salva in baza de date" as UC22
    usecase "Se va trimite un request \n catre baza de date cu corectitudinea \n informatiei din campurile respective" as UC23
    usecase "Formularul va tine \nminte email si parola" as UC24
    usecase "Pagina va afisa un \n pop up cu mesajul \n"Email sau parola gresite" \n si un buton de "Reincearca"" as UC25
    usecase "Fereastra Pop-up \n se va inchide" as UC26
}

package HomePage {
    usecase "Se afiseza Home Page care \n contine in partea stanga un \n NavBar si in centru se \n va afisa cate un div cu \n noutatile si stirile din domeniul auto" as UC15
    usecase "Pagina va deschide \nalta pagina care \ncontine toata informatia \n legata de acea stire" as UC17
    usecase "Se incarca stirile mai vechi, \ndandu-se scroll in jos la paina" as UC18
    usecase "Se incarca stirile actuale,\n dandu-se scroll in sus la pagina" as UC19
}

package 1)Profil_Utilizator {
    usecase "Se afiseaza pagina destinata profilului de \n utilizator care contine poza de profil, numele, \n descriere, detalii despre masina, un buton de \n editare date, un buton de afisare prieteni, buton \n de afisare grupuri si un buton destinat setarilor aplicatiei" as UC1
    usecase "Se va afisa sectiunea de \n editare a datelor si un buton \n de salvare a modificarilor" as UC2
    usecase "Se va trimite un request \n catre baza de date pentru a \n alege utilizatorii care sunt \n asociati cu contul utilizatorului" as UC3
    usecase "Se va afisa pe o pagina \n noua o lista cu acestia \n in ordine alfabetica" as UC4
    usecase "Se va trimite un request \n catre baza de date pentru a \n alege grupurile din care face parte" as UC5
    usecase "Se vor afisa pe o pagina \n noua toate grupurile asociate \n cu contul utilizatorului" as UC6
    usecase "Se va deschide o pagina \n care contine un buton pentru\n schimbarea parolei,un buton \n pentru schimbarea temei paginii si  \n un buton pentru stergerea cotului." as UC7
    usecase "Se va afisa o pagina cu un \n textbox pentru a se introduce \n parola actuala, un textbox pentru \n a se introduce parola noua si un \n buton pentru a salva modificarile facute" as UC8
    usecase "Se va afisa o pagina cu 3 variante \n de alegere: automat, light sau dark" as UC9
    usecase "Aplicatia va avea drept \n culoare principala alb" as UC10
    usecase "Aplicatia va avea drept \n culoare principala gri graphite" as UC11
    usecase "Se va afisa o fereastra cu \n un buton de confirmare" as UC12
    usecase "Se va afisa \n Landing Page" as UC13
    usecase "Se va trimite un request \n catre baza de date pentru \n stergerea email-ului \n si parolei din evidenta" as UC14
}

package 2)Comparare_masini {
    usecase "Se va afisa o pagina care \n contine acelasi NavBar in \n partea stanga iar pe mijloc va \n fi afisat un div impartit in 2 parti: \n prima parte pentru alegerea \n primei masini , a 2 a parte pentru \n alegerea masinii 2 si un \n buton de start comparare" as UC27
    usecase "Se va afisa o lista \n aferenta fiecarui \n tip de informatie" as UC28
    usecase "sub acest div se va afisa \n un alt div care afiseaza \n o poza pentru fiecare masina, \n sub poze se vor afisa brand-ul \n si marca masinilor, iar sub acestea \n se vor afisa informatiile legate de \n anul productiei, informatii legate \n de dimensiuni, informatii ale motoarelor, \n clasa masinilor si siguranta in caz de \n impact. De asemenea, va exista si o rubrica \n de review-uri lasate de proprietarii masinilor." as UC29
    usecase "se va deschide o pagina cu \n mai multe casute, fiecare \n casuta afisand numele utilizatorului, \n rating-ul pe care l-a acordat \n masinii si niste cuvinte." as UC30
}

package 3)Forum {
    usecase "se va afisa o pagina care \n contine acelasi NavBar in partea \n stanga iar pe mijloc vor fi \n afisate mai multe cadrane cu \n diferite subiecte de discutie recente \n si un searchbar pentru a cauta subiecte \n in functie de cuvintele cheie scrise" as UC31
    usecase "se va deschide pagina \n dedicata acelei discutii,\n cu textul integral, \n data postarii si replicile \n oferite de ceilalti utilizatori" as UC32
    usecase "utilizatorului ii este \n permisa scrierea cuvintelor" as UC33
    usecase "se va executa algoritmul \n de cautare pe baza cuvintelor" as UC34
    usecase "se vor afisa subiectele care \n au o potrivire de cuvinte" as UC35
}

'Landing Page
u -down--> UC20: Introduce linkul aplicatiei \n in browser si apasa enter
u -down--> UC21: Apasa pe butonul \n 'Creare Cont'
u -down--> UC22:Completeaza campurile pentru \ninregistrare si apasa 'Inregistrare'
UC22 -down--> UC20
u -down--> UC23:Completeaza campurile pentru \nautentificare si apasa 'Autentificare'
u -down--> UC24:Bifeaza checkbox\n-ul 'Tine-ma minte'
UC23 -down--> UC25:Daca datele \n sunt gresite
UC23 -down--> UC15:Daca datele \nsunt corecte
u -down-->UC26:Apasa butonul \n 'Reincearca'


:Admin: --> (Se vor afisa stirile in Home \n Page in partea de sus):Introduce noutati si \n stiri din domeniul auto in \n div-urile din mijlocul \n Home Page-ului
:Admin: --> (Se vor afisa informatiile \n legate de masini in pagina \n de Comparare masini):Introduce informatiile \n masinilor in baza de date


'Home Page
u -down--> UC17:Apasa pe \n orice div din \n din Home Page.
u -down--> UC18:Se afla in top \n sau mid pe \n Home Page si \n da scroll-down
u -down--> UC19:Se afla in bottom \n sau mid pe Home \n Page si da scroll-up


'Profil Utilizator
u -up--> UC1:Apasa pe butonul \n 1.Profil utilizator
u -up--> UC2:Apasa butonul de editare profil
u -up--> UC3:Apasa butonul afisare prieteni
UC3 -up--> UC4
u -up--> UC5:Apasa pe butonul de afisare grupuri
UC5 -up--> UC6
u -up--> UC7:Apasa pe butonul de setari ale aplicatiei
u -up--> UC8:Apasa butonul de schimbare a parolei
u -up--> UC9:Apasa pe butonul de schimbare a temei paginii
u -up--> UC10:Alege tema light
u -up--> UC11:Alege tema dark
u -up--> UC12:Apasa butonul de stergere cont
u -up--> UC13:Apasa butonul de confirmare a stergerii contului
UC13 -up--> UC14


'Comparare masini
u -down--> UC27:Apasa pe butonul \n 2.Comparare masini
u -down--> UC28:La apasarea \n fiecarui dropdown
u -down--> UC29:La apasarea butonului \n de comparare masini
u -down--> UC30:La apasarea ste-\nlutelor de rating


'Forum
u -up--> UC31:Apasa pe \n butonul 3.Forum
u -up--> UC32:La accesarea \n unui subiect
u -up--> UC33:La apasarea \n searchbar-ului
u -up--> UC34:Cand utilizatorul va \n apasa enter la searchbar
UC34 -up-->UC35

@enduml
'gandeste d.p.d.v al aplicatiei(gandeste cum fac ele in spate)
'scriem si despre resursele web pe care le foloseste(de exemplu:foloseste imaginea din sursa x, ia info din x)
'use case = descrie functionalitate
'use case= caz de utilizare
'gandeste te la actori, daca utilizatorul este cel care face toate actiunile
'actorul este declansatorul